
>data Campus = SingleRoom Room | MultiRoom Origin [(Campus, Placement, Alignment)]  deriving (Eq, Show)
>data Origin = Origin Int Int Int  deriving (Eq, Show)

>data Room = Room RoomDims Corners Pillars Walls deriving (Eq, Show)
>data RoomDims = RoomDims AB AD AE ThicknessAB ThicknessAD ThicknessAE deriving (Eq, Show)
>data AB = AB Int  deriving (Eq, Show)
>data AD = AD Int  deriving (Eq, Show)
>data AE = AE Int  deriving (Eq, Show)
>data ThicknessAB = ThicknessAB (Int, Int) deriving (Eq, Show)
>data ThicknessAD = ThicknessAD (Int, Int) deriving (Eq, Show)
>data ThicknessAE = ThicknessAE (Int, Int) deriving (Eq, Show)

>data Corners = Corners CornerA CornerB CornerC CornerD CornerE CornerF CornerG CornerH deriving (Eq, Show)
>data Pillars = Pillars PillarAB PillarAD PillarAE PillarBC PillarBF PillarCD PillarCG PillarDH PillarEF PillarEH PillarFG PillarGH deriving (Eq, Show)
>data Walls   = Walls (WallABCD, Alignment) (WallABFE, Alignment) (WallADHE, Alignment) (WallEFGH, Alignment) (WallBCGF, Alignment) (WallDCGH, Alignment) deriving (Eq, Show)

>data CC = CA | CB | CC | CD deriving (Eq, Show)
>data Doors = Doors [(Door, Placement)] deriving (Eq, Show)
>data Door = Door Block deriving (Eq, Show)
>data Block = Block AB AD AE deriving (Eq, Show)
>data Alignment = Alignment CC CC CC CC deriving (Eq, Show)
>data Placement = Placement AB AD AE Alignment deriving (Eq, Show)
>data CornerA = CornerA Block deriving (Eq, Show)
>data CornerB = CornerB Block deriving (Eq, Show)
>data CornerC = CornerC Block deriving (Eq, Show)
>data CornerD = CornerD Block deriving (Eq, Show)
>data CornerE = CornerE Block deriving (Eq, Show)
>data CornerF = CornerF Block deriving (Eq, Show)
>data CornerG = CornerG Block deriving (Eq, Show)
>data CornerH = CornerH Block deriving (Eq, Show)

>data PillarAB = PillarAB Block deriving (Eq, Show)
>data PillarAD = PillarAD Block deriving (Eq, Show)
>data PillarAE = PillarAE Block deriving (Eq, Show)
>data PillarBC = PillarBC Block deriving (Eq, Show)
>data PillarBF = PillarBF Block deriving (Eq, Show)
>data PillarCD = PillarCD Block deriving (Eq, Show)
>data PillarCG = PillarCG Block deriving (Eq, Show)
>data PillarDH = PillarDH Block deriving (Eq, Show)
>data PillarEF = PillarEF Block deriving (Eq, Show)
>data PillarEH = PillarEH Block deriving (Eq, Show)
>data PillarFG = PillarFG Block deriving (Eq, Show)
>data PillarGH = PillarGH Block deriving (Eq, Show)

>data WallABCD = WallABCD Block Doors deriving (Eq, Show)
>data WallABFE = WallABFE Block Doors deriving (Eq, Show)
>data WallADHE = WallADHE Block Doors deriving (Eq, Show)
>data WallEFGH = WallEFGH Block Doors deriving (Eq, Show)
>data WallBCGF = WallBCGF Block Doors deriving (Eq, Show)
>data WallDCGH = WallDCGH Block Doors deriving (Eq, Show)

